name: mininotes

base: core24

adopt-info: mininotes
title: MiniNotes
license: MIT
contact:
  - https://t.me/Ahmad_Abdelbary
issues:
  - https://github.com/ahmadabdelbary2001/mininote/issues
source-code:
  - https://github.com/ahmadabdelbary2001/mininote
website:
  - https://github.com/ahmadabdelbary2001/mininote

summary: Offline-first notes application

description: |
  MiniNotes is a small offline-first notes application built
  with Qt, QML, C++ and SQLite.

grade: stable
confinement: strict

icon: assets/icons/mininotes.svg

apps:
  mininotes:
    command: usr/bin/mininotes

    desktop: usr/share/applications/io.github.ahmadabdelbary2001.mininote.desktop

    extensions:
      - kde-neon-6

    environment:
      QT_QUICK_BACKEND: software
      QT_QUICK_CONTROLS_STYLE: Basic

parts:
  mininotes:
    plugin: cmake

    source: .

    override-pull: |
      craftctl default

      VERSION="$(sed -nE 's/^project\(mininotes VERSION ([0-9.]+).*/\1/p' "$CRAFT_PART_SRC/CMakeLists.txt")"

      test -n "$VERSION"

      craftctl set version="$VERSION"

    build-packages:
      - libqt6sql6-sqlite

    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DMININOTES_BUILD_TESTS=OFF
      - -DMININOTES_PACKAGE=ON
